# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=50, null=True, verbose_name='用户性别'),
        ),
    ]
