# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-16 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='gt_desc',
            field=models.TextField(null=True, verbose_name='类型描述'),
        ),
    ]
