# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-19 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('recv_name', models.CharField(max_length=255, verbose_name='收货人')),
                ('recv_address', models.CharField(max_length=255, verbose_name='收货地址')),
                ('recv_phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('recv_remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('totale', models.IntegerField(verbose_name='总计金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单单项id')),
                ('oi_goods_id', models.CharField(max_length=100, verbose_name='购买商品编号')),
                ('oi_goods_image_path', models.CharField(max_length=255, verbose_name='购买商品图片')),
                ('oi_goods_name', models.CharField(max_length=255, verbose_name='购买商品名称')),
                ('oi_goods_price', models.IntegerField(verbose_name='购买商品单价')),
                ('oi_goods_count', models.IntegerField(verbose_name='购买商品数量')),
                ('deal_price', models.IntegerField(verbose_name='成交价格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyOrder.Order', verbose_name='所属订单')),
            ],
        ),
    ]
