# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='店铺编号')),
                ('name', models.CharField(max_length=255, verbose_name='店铺名称')),
                ('cover', models.ImageField(default='static/images/Store/default.jpg', upload_to='static/images/Store/', verbose_name='店铺封面')),
                ('intro', models.TextField(verbose_name='店铺描述')),
                ('opener_time', models.DateTimeField(auto_now_add=True, verbose_name='开店时间')),
                ('status', models.BooleanField(default=True, verbose_name='店铺状态')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
